#!/usr/bin/env bash
# Writes ~/.hermes/cli-config.yaml from env vars on every container start,
# then keeps the container alive so `docker exec -it -u hermes hermes bash` works.
set -euo pipefail

BASE_URL="${INFERENCE_BASE_URL:-http://ollama:11434/v1}"
PROVIDER="${INFERENCE_PROVIDER:-ollama}"
MODEL="${INFERENCE_MODEL:-}"
OLLAMA_MDL="${OLLAMA_MODEL:-$MODEL}"
LLAMACPP_MDL="${LLAMACPP_MODEL:-}"
CTX="${LLAMACPP_CTX:-65536}"

# Map our provider names to hermes provider names
[[ "$PROVIDER" == "llamacpp" ]] && HERMES_PROVIDER="custom" || HERMES_PROVIDER="ollama"

mkdir -p "${HOME}/.hermes"
CONFIG="${HOME}/.hermes/cli-config.yaml"

{
    printf '# Auto-generated by local-ai-stack entrypoint — edit to customise.\n'
    printf 'model:\n'
    printf '  default: "%s"\n'  "$MODEL"
    printf '  provider: "%s"\n' "$HERMES_PROVIDER"
    printf '  base_url: "%s"\n' "$BASE_URL"
    printf '  api_key: ""\n'
    if [[ "$PROVIDER" == "llamacpp" ]]; then
        printf '  context_length: %s\n' "$CTX"
    fi
    printf '\nmodel_aliases:\n'
    if [[ -n "$OLLAMA_MDL" ]]; then
        printf '  ollama:\n'
        printf '    model: "%s"\n'   "$OLLAMA_MDL"
        printf '    provider: "ollama"\n'
        printf '    base_url: "http://ollama:11434/v1"\n'
    fi
    if [[ -n "$LLAMACPP_MDL" ]]; then
        printf '  llamacpp:\n'
        printf '    model: "%s"\n'         "$LLAMACPP_MDL"
        printf '    provider: "custom"\n'
        printf '    base_url: "http://llamacpp:8080/v1"\n'
        printf '    context_length: %s\n'  "$CTX"
    fi
} > "$CONFIG"

exec sleep infinity
