#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
CERTS_DIR="$ROOT_DIR/config/nginx/certs"

bold() { echo -e "\033[1m$*\033[0m"; }
info() { echo -e "  \033[36m→\033[0m $*"; }
ok()   { echo -e "  \033[32m✓\033[0m $*"; }
warn() { echo -e "  \033[33m!\033[0m $*"; }

DOMAINS=(
    "ollama.localai"
    "llamacpp.localai"
    "chat.localai"
    "searxng.localai"
    "hermes.localai"
    "www.localai"
    "comfyui.localai"
    "design.localai"
)

echo ""
bold "Local Domains Setup"
echo "────────────────────────────────────────"

# ── mkcert ────────────────────────────────────────────────────────────────

if ! command -v mkcert &>/dev/null; then
    warn "mkcert is not installed."
    read -rp "  Install mkcert now? [Y/n]: " INSTALL_MKCERT
    INSTALL_MKCERT=${INSTALL_MKCERT:-Y}
    if [[ "$INSTALL_MKCERT" =~ ^[Yy]$ ]]; then
        if command -v apt-get &>/dev/null; then
            sudo apt-get update -qq && sudo apt-get install -y mkcert libnss3-tools
        elif command -v brew &>/dev/null; then
            brew install mkcert nss
        else
            warn "Cannot auto-install mkcert. Install it manually: https://github.com/FiloSottile/mkcert"
            exit 1
        fi
    else
        warn "Skipping — local domains will run on HTTP only."
        exit 0
    fi
fi
ok "mkcert is available"

# ── Install local CA ───────────────────────────────────────────────────────

info "Installing local certificate authority..."
mkcert -install
ok "Local CA installed"

# ── Generate certs ────────────────────────────────────────────────────────

mkdir -p "$CERTS_DIR"
info "Generating certificates in $CERTS_DIR..."
(
    cd "$CERTS_DIR"
    mkcert "${DOMAINS[@]}"
    # mkcert outputs a single cert covering all domains
    # Rename to predictable names for nginx
    mv *+*.pem localai.pem   2>/dev/null || true
    mv *+*-key.pem localai-key.pem 2>/dev/null || true
)
ok "Certificates generated"

# ── /etc/hosts ────────────────────────────────────────────────────────────

info "Adding entries to /etc/hosts (requires sudo)..."
HOSTS_BLOCK_START="# BEGIN local-ai-stack"
HOSTS_BLOCK_END="# END local-ai-stack"

# Remove existing block if present
if grep -q "$HOSTS_BLOCK_START" /etc/hosts; then
    sudo sed -i "/$HOSTS_BLOCK_START/,/$HOSTS_BLOCK_END/d" /etc/hosts
    info "Removed previous /etc/hosts entries"
fi

{
    echo "$HOSTS_BLOCK_START"
    for domain in "${DOMAINS[@]}"; do
        echo "127.0.0.1  $domain"
    done
    echo "$HOSTS_BLOCK_END"
} | sudo tee -a /etc/hosts > /dev/null
ok "/etc/hosts updated"

# ── nginx SSL config ───────────────────────────────────────────────────────

SSL_CONF="$ROOT_DIR/config/nginx/conf.d/ssl.conf"
info "Writing SSL server blocks to $SSL_CONF..."

cat > "$SSL_CONF" <<'NGINX'
# Auto-generated by setup-local-domains.sh
# Redirect all HTTP to HTTPS for .localai domains
server {
    listen 80;
    server_name *.localai;
    return 301 https://$host$request_uri;
}

ssl_certificate     /etc/nginx/certs/localai.pem;
ssl_certificate_key /etc/nginx/certs/localai-key.pem;
ssl_protocols       TLSv1.2 TLSv1.3;
ssl_ciphers         HIGH:!aNULL:!MD5;

server { listen 443 ssl; server_name chat.localai;    location / { proxy_pass http://openwebui:8080;    proxy_set_header Host $host; proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection upgrade; proxy_read_timeout 300s; } }
server { listen 443 ssl; server_name ollama.localai;  location / { proxy_pass http://ollama:11434;      proxy_set_header Host $host; proxy_read_timeout 300s; } }
server { listen 443 ssl; server_name llamacpp.localai; location / { proxy_pass http://llamacpp:8080;   proxy_set_header Host $host; proxy_read_timeout 300s; } }
server { listen 443 ssl; server_name searxng.localai; location / { proxy_pass http://searxng:8080;     proxy_set_header Host $host; } }
server { listen 443 ssl; server_name hermes.localai;  location / { proxy_pass http://hermes-webui:8787; proxy_set_header Host $host; proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection upgrade; proxy_read_timeout 300s; } }
server { listen 443 ssl; server_name www.localai;     location / { proxy_pass http://ubuntu-server:80;  proxy_set_header Host $host; } }
server { listen 443 ssl; server_name comfyui.localai; location / { proxy_pass http://comfyui:8188;     proxy_set_header Host $host; proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection upgrade; } }
server { listen 443 ssl; server_name design.localai;  location / { proxy_pass http://opendesign:7456;  proxy_set_header Host $host; proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection upgrade; } }
NGINX

ok "SSL config written"

# ── Reload nginx ───────────────────────────────────────────────────────────

if docker ps -q --filter name=nginx | grep -q .; then
    info "Reloading nginx..."
    docker exec nginx nginx -s reload
    ok "nginx reloaded"
fi

echo ""
bold "Local domains ready!"
for domain in "${DOMAINS[@]}"; do
    echo "  https://$domain"
done
echo ""
